const GET_DAY = 'GET_DAY'
const GET_DAY_REQUEST = 'GET_DAY_REQUEST'
const GET_DAY_SUCCESS_FOUND = 'GET_DAY_SUCCESS_FOUND'
const GET_DAY_SUCCESS_NOT_FOUND = 'GET_DAY_SUCCESS_NOT_FOUND'

export {
  GET_DAY,
  GET_DAY_REQUEST,
  GET_DAY_SUCCESS_FOUND,
  GET_DAY_SUCCESS_NOT_FOUND
}