default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: demo
  password: P@ssword!1
  host: localhost

development:
  <<: *default
  database: emotion_tracker

test:
  <<: *default
  database: emotion_tracker_test

production:
  <<: *default
  database: emotion_tracker_production
  username: <%= ENV['EMOTION_TRACKER_DATABASE_USERNAME'] %>
  password: <%= ENV['EMOTION_TRACKER_DATABASE_PASSWORD'] %>