# This file was generated by the `rails generate rspec:install` command.
# Conventionally, all specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper`, which ensures this file is always loaded.

# Keep this file lightweight to minimize boot time. Load additional dependencies in separate helper files.

RSpec.configure do |config|
  # Configuration for rspec-expectations
  config.expect_with :rspec do |expectations|
    # Include text from helper methods in custom matcher descriptions
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # Configuration for rspec-mocks
  config.mock_with :rspec do |mocks|
    # Prevent mocking or stubbing methods that don't exist
    mocks.verify_partial_doubles = true
  end

  # Metadata behavior: inherited by child groups instead of triggering auto-inclusion
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Uncomment the settings below to customize RSpec behavior

  # Run only examples with `:focus` metadata, when specified
  # config.filter_run_when_matching :focus

  # Persist state between runs to enable `--only-failures` and `--next-failure` CLI options
  # config.example_status_persistence_file_path = "spec/examples.txt"

  # Disable monkey-patching for stricter syntax enforcement
  # config.disable_monkey_patching!

  # Use detailed output for single-file runs
  # if config.files_to_run.one?
  #   config.default_formatter = "doc"
  # end

  # Profile the 10 slowest examples at the end of each test run
  # config.profile_examples = 10

  # Run specs in random order to surface order dependencies
  config.order = :random

  # Seed global randomization to debug order-dependent failures
  # Kernel.srand config.seed
end